### ISSUE TITLE
No button to load payment methods

### ISSUE THREAD

**Issue by jca116** [ICEPAY/Magento-2#1] opened 2016-11-16 08:10 UTC
In the configuration there is no option shown to load the payment methods
We are using Magento version 2.1.2 and this plugin version 1.0.0b

In the configuration it only says "Configuration information   Please read the advanced manual"
In Magento 1.9 there was a button to load payment methods, now there is nothing.

Can you please help out asap as we already lost a lot of time trying to get an answer by regular support from Icepay and they have now told us to post the issue here.

**Comment by tsygankov** [comment] 2016-11-16 13:28
Hi jca116,

Thank you for testing the beta version of the module! Your feedback is very important to us!

The user manual for ICEPAY Magento 2 payment module is not yet ready, but we will try to answer all your questions here.

To load payment methods in v1.0.0.b you need to navigate to the ICEPAY payment method list:

![1](https://cloud.githubusercontent.com/assets/15112699/20348966/d8a68b82-ac10-11e6-90c1-ca1fe732f28d.PNG)

Then please press SYNC button:

![2](https://cloud.githubusercontent.com/assets/15112699/20348968/dddcc0b2-ac10-11e6-9e3d-e0390eda5c6a.PNG)

Please let me know if you have any other questions.

/Stan

**Comment by tsygankov** [comment] 2016-11-16 13:33
Just for your information: there is a known bug in the v1.0.0.b - payment module is not working if there are downloadable products in your cart. We will fix it very soon.

**Comment by jca116** [comment] 2016-11-16 17:22
Ok, thanks for the quick response.
Found that button now but that's also not working.
Nothing in logfiles, no errors, just nothing.

How can I find out what can be wrong?
All Magento checks say the module is installed correctly and I see no errors in any of the logfiles or admin interface

Note: we're not selling downloadable products so that will be ok.
There are no demo products loaded, etc. only our own products.

We are running a multi-shop environment in 'production' setting.

**Comment by tsygankov** [comment] 2016-11-16 21:40
Can you please check if your ICEPAY merchant account settings are filled in?

 System > Configuration > Sales > Payment Methods

![ip](https://cloud.githubusercontent.com/assets/15112699/20366590/83db7af6-ac54-11e6-9da3-db3ef2dc6938.PNG)

Please also check if you have the latest version of the module. ~23 days ago we added a bugfix:  "ECC-96 Bugfix: Payment Method grid is empty".

So payment methods won't be shown in Magento 2.1.x if you have older version of the module. 

When the problem with downloadable products will be fixed we will release v1.0.0 beta 2

**Comment by jca116** [comment] 2016-11-16 22:15
Yes, all settings are there and ok.
We already run 3 separate Magento 1.9 installs with 7 or 8 webshops, all with Icepay plugin for payments so we have experience in those settings per webshop ;)

I downloaded this module 2 weeks ago on Wednesday, Nov. 02 using the link on the Icepay website:
https://github.com/ICEPAYdev/Magento-2/releases/download/1.0.0b/1.0.0b.zip

Link is shown on download button here:
https://icepay.com/nl/webshop-modules/magento-2/

**Comment by jca116** [comment] 2016-11-16 22:42
I have checked last commit with this fix:
https://github.com/ICEPAYdev/Magento-2/commit/fa01046f5525987bbf5cf32fc888d673343f6cd0


I see that change is NOT in the code we are using on our server:

    
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">paymentmethod_listing.paymentmethod_listing_data_source</item>
            <item name="paymentmethods" xsi:type="string">paymentmethod_listing.paymentmethod_listing_data_source</item>
        </item>
        <item name="spinner" xsi:type="string">paymentmethod_columns</item>
        <item name="buttons" xsi:type="array">


I have added the line by hand, regenerated DI, etc. and it now works !
We have grid with payment methods now

Only run into next issue: when I create an order and select Icepay methods (iDeal, Bancontact, whatever) the order can not be posted. The screen just sort of 'blinks' but stays on the select-payment page as if some field of the form is not filled correctly.

**Comment by jca116** [comment] 2016-11-16 22:53
Here are screenshots from Firebug that shows the PUT action after posting the order and the response.
The response on the PUT is 'route unknown' which (judging on the info) probably means it doesn't have a route to icepay_icpcore_ideal  ?

![screenshot_icepay_magento2_error_payment](https://cloud.githubusercontent.com/assets/5918395/20369068/57cc6350-ac57-11e6-97c5-3c4d50f685af.png)

![screenshot_response_icepay_error_payment](https://cloud.githubusercontent.com/assets/5918395/20369168/d73c9448-ac57-11e6-925a-80773fd9aacd.png)

**Comment by jca116** [comment] 2016-11-16 22:59
FYI: when I choose bank-payment the order is executed normally, so the rest of the shop system is working fine

**Comment by tsygankov** [comment] 2016-11-17 10:52
Please check the commit https://github.com/ICEPAYdev/Magento-2/commit/7a378722c273635e4e03de818ef81a638de51719

Please don't forget to refresh Magento cache and static content.

**Comment by jca116** [comment] 2016-11-17 20:06
Ok, I now have installed the dev branch because the official release in zip-file also didn't have this commit.

It works now but there are still issues:
- When creditcard is disabled I can not use other payment method like iDeal because of javascript error:
TypeError: window.checkoutConfig.payment.icepay.creditcard is undefined
	$.mage.redirect(window.checkoutConfig.payment.icepay.creditcard.redirectUrl);
Customer is stuck on the payment-select page and can not pay the order

![screenshot_magento2_icepay_creditcard_disabled](https://cloud.githubusercontent.com/assets/5918395/20404941/46acc01e-ad07-11e6-8e8e-533571710303.png)

When returning from payment I get the homepage, looks like the landing-page is not  available?

FYI: we are using a special theme package called Porto, maybe that gives issues with the Icepay plugin?:
http://www.newsmartwave.net/magento2/porto/demo15_en/

**Comment by tsygankov** [comment] 2016-11-18 11:32
Currently we are trying to reproduce the issue on our test environment. I will get back to you soon.

**Comment by tsygankov** [comment] 2016-11-19 02:07
Hi jca116,

> I downloaded this module 2 weeks ago on Wednesday, Nov. 02 using the link on the Icepay website:
https://github.com/ICEPAYdev/Magento-2/releases/download/1.0.0b/1.0.0b.zip

Looks like the link is pointing to an old version if the module, I will ask my colleagues fix it. We released a first beta version (1.0.0b) some time ago. This version was created for Magento 2.0.x, compatibility with Magento 2.1.x was not tested. Since then we have fixed several bugs and also tested compatibility with Magento 2.1.x.

We were trying to reproduce the issue that you described in your last comment. Our test engineer somehow could reproduce it once (same problem, but another payment method), however when he tried to repeat the same actions again the problem dissipated and we could not reproduce it any more. We assume that the problem can be somehow related to the cashed JS files that remained from the 1.0.0b installation. 

Can you please provide a link to the website where the problem appears (if the website it's publicly available)? We will try to check all ICEPAY JS files and compare them with the files on our test environment. Please do not publish any other sensitive information (URLs, passwords and etc) here, please send us an email to modules@icepay.com. 

Please let me know if this problem needs to be solved urgently.

**Comment by tsygankov** [comment] 2016-11-21 16:13
Hi jca116,

Do you have any updates?

**Comment by jca116** [comment] 2016-11-22 09:36
Hell tsygankov,

Sorry for the late reply but I was very busy last days.
I had to de-install the Icepay plugin from the webshop because everything had become very unstable.
After de-install all was ok again but that webshop is live now with other payment methods and I can not use it for experiments.

We have an other customer coming up for migration to Magento 2.1 so I can install the latest sources there soon. Don't know when that will be, initial setup has been planned for this week but don't know if we have a full working shop with products availble.

I will inform you as soon as I know next steps.

**Comment by tsygankov** [comment] 2016-11-23 00:19
Finally we have reproduced this issue. The bug will be fixed ASAP..

**Comment by jca116** [comment] 2016-11-23 13:43
Ok, great!

**Comment by tsygankov** [comment] 2017-05-22 21:19
The problem should be fixed in the latest version of the module. Please reopen this issue if this is still a problem for you.

**Closed by tsygankov** 2017-05-22 21:19 UTC
